In [6]:
import cv2
import numpy as np
import glob
import matplotlib.pyplot as plt


In [7]:
# Dimensions du quadrillage (coins intérieurs)
chessboard_size = (6, 8)  # 9x6 coins

# Préparation des points 3D réels
objp = np.zeros((chessboard_size[0]*chessboard_size[1], 3), np.float32)
objp[:, :2] = np.mgrid[0:chessboard_size[0], 0:chessboard_size[1]].T.reshape(-1, 2)

objpoints = []  # Points 3D
imgpoints = []  # Points 2D

# Charge les images du quadrillage
images = glob.glob('./data_calibration/*.jpg')

images

['./data_calibration/20250402_135630.jpg',
 './data_calibration/20250402_135634.jpg',
 './data_calibration/20250402_135634(0).jpg',
 './data_calibration/20250402_135632(0).jpg',
 './data_calibration/20250402_135635.jpg',
 './data_calibration/20250402_135633.jpg',
 './data_calibration/20250402_135630(1).jpg',
 './data_calibration/20250402_135632.jpg',
 './data_calibration/20250402_135631.jpg',
 './data_calibration/20250402_135631(0).jpg',
 './data_calibration/20250402_135630(0).jpg']

In [8]:
i = 0

for fname in images:
    i += 1
    print(f"Une image de plus : {i}/{len(images)}")
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    ret, corners = cv2.findChessboardCorners(gray, chessboard_size, None)
    if ret:
        objpoints.append(objp)
        imgpoints.append(corners)

# Calibrage de la caméra
ret, K, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

print("Matrice intrinsèque K :\n", K)

Une image de plus : 1/11
Une image de plus : 2/11
Une image de plus : 3/11
Une image de plus : 4/11
Une image de plus : 5/11
Une image de plus : 6/11
Une image de plus : 7/11
Une image de plus : 8/11
Une image de plus : 9/11
Une image de plus : 10/11
Une image de plus : 11/11
Matrice intrinsèque K :
 [[3.60897911e+03 0.00000000e+00 8.59539453e+02]
 [0.00000000e+00 3.60991762e+03 2.24266702e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
